### ISSUE TITLE
Return config_diff for scheduled execution

### ISSUE THREAD

**Issue by muga** [treasure-data/embulk-input-mixpanel#12]
To execute Embulk and the plugin periodically, we should return better config_diff to Embulk.
reference: https://github.com/treasure-data/embulk-input-marketo/issues/18

**Comment by yoshihara** [comment]
Thank you for issue.

I have an idea for this, please check https://github.com/treasure-data/embulk-input-marketo/issues/18#issuecomment-130511589

**Comment by yoshihara** [comment]
We implemented this. Please wait for release...

**Comment by yoshihara** [comment]
We released [0.2.0](https://rubygems.org/gems/embulk-input-mixpanel). Thanks for reporting!
