### ISSUE TITLE
Catch unguessed coulumns' data

### ISSUE THREAD

**Issue by yoshihara** [treasure-data/embulk-input-mixpanel#29]
Mixpanel supports custom columns, so any columns don't exist when guessing by Embulk.
- Add String column and add unguessed columns' data
- Show warn message about unguessed columns'info to Embulk.logger

**Comment by yoshihara** [comment]
@kiyoto I supported it by #30. So please wait next release.

**Comment by uu59** [comment]
this is included by 0.3.4.
